// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// set_ipums_var_attributes_
DataFrame set_ipums_var_attributes_(DataFrame x, DataFrame var_info, bool haven_v2);
RcppExport SEXP _ipumsr_set_ipums_var_attributes_(SEXP xSEXP, SEXP var_infoSEXP, SEXP haven_v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type var_info(var_infoSEXP);
    Rcpp::traits::input_parameter< bool >::type haven_v2(haven_v2SEXP);
    rcpp_result_gen = Rcpp::wrap(set_ipums_var_attributes_(x, var_info, haven_v2));
    return rcpp_result_gen;
END_RCPP
}
// set_imp_decim_
DataFrame set_imp_decim_(DataFrame x, DataFrame var_info);
RcppExport SEXP _ipumsr_set_imp_decim_(SEXP xSEXP, SEXP var_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type var_info(var_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(set_imp_decim_(x, var_info));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ipumsr_set_ipums_var_attributes_", (DL_FUNC) &_ipumsr_set_ipums_var_attributes_, 3},
    {"_ipumsr_set_imp_decim_", (DL_FUNC) &_ipumsr_set_imp_decim_, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ipumsr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
