# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

raw_to_df_hier_list <- function(raw_, rt_info_, var_info_, encoding_) {
    .Call('_ripums_raw_to_df_hier_list', PACKAGE = 'ripums', raw_, rt_info_, var_info_, encoding_)
}

raw_to_df_hier_long <- function(raw_, num_vars, rt_info_, var_info_, encoding_) {
    .Call('_ripums_raw_to_df_hier_long', PACKAGE = 'ripums', raw_, num_vars, rt_info_, var_info_, encoding_)
}

